# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'FindNearbyPlacesApp' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )
#   end
# end

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'

# Force pods to build for arm64 simulator and arm64 device


target 'FindNearbyPlacesApp' do
  config = use_native_modules!

  # React Native Maps
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps', '7.4.0'  # Required for react-native-maps
  
  # React Native Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Add specific permissions you need
  require_relative '../node_modules/react-native-permissions/scripts/setup'
  setup_permissions([
    'LocationWhenInUse',
    # 'LocationAlways',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # Fix architecture issues
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "armv7"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
    end
    
    # React Native post install
    react_native_post_install(installer)
  end
end